# Generated by Django 5.2.5 on 2025-08-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationeryhub', '0002_featuredproduct_trendingproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school_products/')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
