# Generated by Django 5.2.5 on 2025-08-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationeryhub', '0003_schoolproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='team/')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
    ]
