# Generated by Django 5.2.5 on 2025-08-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationeryhub', '0005_aboutsection_aboutsectionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
