# Generated by Django 5.2.5 on 2025-08-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationeryhub', '0006_alter_aboutsection_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
