# Generated by Django 5.2.5 on 2025-08-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationeryhub', '0008_contactinfo_emailaddress_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='icon',
            field=models.CharField(help_text='Bootstrap icon class, e.g. bi-geo-alt', max_length=50),
        ),
    ]
