# Generated by Django 5.2.5 on 2025-08-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationeryhub', '0009_alter_contactinfo_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
