# Generated by Django 5.2.5 on 2025-09-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationeryhub', '0015_billingdetails_user_order_status_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
